#ifndef DEFINITION
#define DEFINITION

#include "timer.h"
#include "omp.h"
#include "string"
#include <cstdlib>
#include <cmath>
#include <complex>
/* Definitions of consts */

typedef double REAL;
#define MKL_Complex16 std::complex<double> // Define MKL_Complex16 as complex<Real>.
// #define MKL_Complex MKL_Complex16 // Rename MKL_Complex16 as MKL_Complex
#define COMPLEX MKL_Complex16

#define _SPIN_N_ 0.5  // nucleon spin
#define _ISOSPIN_N_ 0.5  // nucleon isospin
#define _SPIN_D_ 1.0  // deuteron spin
#define _ISOSPIN_D_ 0.0  // deuteron isospin
// #define _AvgMassN_ 939.0
#define _AvgMassN_ 938.918725
#define _HBARC_ 197.3286

#define _FLOAT_ZERO_    1.0e-6
#define _ERROR_Gqqx_    1.0E-8 // Relative ERROR in Gqqx
#define _GAULEG_EPS_    1.0E-13 // Used in rootfinding for GAULEG mesh
#define _3NJ_EPS_       1.0E-13
#define _INTZ_EPS_      1.0E-13
#define _tMat_ZERO_     1.0E-30
#define _momentum_EPS_  1.0E-13

#define _MAXN_FACTBL_   42
#define _MAXN_UparaL_   100

// Number of quantum numbers for an alpha-labeled channel, used in homogeneous
// equation
#define _N_QMN_CHN_     10
// #define _N_QMN_CHN_TOT_ 10 // Number of QNs used in solving inhomogeneous eqn

/* factor array {1!, 2!, 3!, ..., _MAXN_FACTBL_!}. Generated by facLabel() in 3nj.
Make sure that N in facArray[N] larger than 4 * L_max + 4 and smaller than 45 */
extern unsigned long long int facArray[_MAXN_FACTBL_];
// #define _TIMER_COL_ "                                    ["

//#define OMP_NUM_THREADS 4

#endif
