# Bingwei Long  08/30/2020
# Bingwei Long  Dec 20/2017

include ../../common.Makefile

DEFOBJS = feb_type.o \
          nneft_phyconst.o \
          nneft_type.o

defmods : $(DEFOBJS)

feb_type.o :

nneft_type.o : feb_type.o

nneft_phyconst.o : nneft_type.o
