include ../makefile.common


# allobj: 3nj.o csvReader.o gaussIntegral.o mathFunc.o matOperator.o spline.o timer.o msg.o delta.o
allobj: 3nj.o csvReader.o gaussIntegral.o mathFunc.o matOperator.o spline.o msg.o iodrv.o delta.o

3nj.o: 3nj.h def.h
csvReader.o:
gaussIntegral.o: gaussIntegral.h def.h
mathFunc.o:
matOperator.o:
spline.o: spline.h def.h
iodrv.o : def.h
delta.o : delta.h def.h 3nj.h

# timer.o:
